require: 
  - 'rubocop-rails'
  - 'rubocop-factory_bot'
  - 'rubocop-rspec'
  - 'rubocop-md'

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
  Exclude:
    - "**/*_spec.rb"
    - "db/**/*"
    - "config/**/*"

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
    - "db/**/*"

Metrics/MethodLength:
  Exclude:
    - "**/*_spec.rb"
    - "db/**/*"

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable

Markdown:
  WarnInvalid: true
  Autodetect: true

Lint/Void:
  Exclude:
    - '*.md'
