require: 
  - 'rubocop-rails'
  - 'rubocop-factory_bot'
  - 'rubocop-rspec'
  - 'rubocop-md'

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable

Markdown:
  WarnInvalid: true
  Autodetect: true

Lint/Void:
  Exclude:
    - '*.md'