version: '3.4'

x-backend:
  &backend
  build:
    context: .
    dockerfile: Dockerfile.dev
  environment:
    RAILS_ENV: development
    DB_USERNAME: postgres
    DB_PASSWORD: secret
    DB_HOST: db
    DB_PORT: 5432
    DB_NAME: desconto_inss
    SECRET_KEY_BASE: STUB
  restart: on-failure:3
  stdin_open: true
  tty: true
  volumes:
    - .:/backend:rw
    - bundle_cache:/bundle

services:
  backend:
    <<: *backend
    ports:
      - '3000:3000'
    depends_on:
      - db
      - sidekiq

  db:
    image: postgres:11.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
  redis:
    image: 'redis:5.0-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  sidekiq:
    <<: *backend
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
      
volumes:
  bundle_cache:
  postgres:
  redis: